---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mastermapr

<!-- badges: start -->
<!-- badges: end -->

The goal of mastermapr is to make it easy to get your OS data imported into open source software for reproducible data science and analysis (#rspatial).

## Installation

You can install the development version of mastermapr from [GitHub](https://github.com/) with:

```r
# install.packages("devtools")
devtools::install_github("acteng/mastermapr")
```

## Example

This is a basic example which shows you can read in road data for GB with the package:

```{r example, eval=FALSE}
library(mastermapr)
# This takes around 30 s on decent laptop as of 2023
# so should be around 10 min for full dataset:
system.time({
  mm_data = mm_read(directory, pattern = "RoadLink", n_files = 8) # 5% of GB files
})
# saveRDS(mm_data, "mm_data_RoadLink.Rds")
```

```{r, eval=FALSE, echo=FALSE}
system.time({
  mm_data = mm_read(directory, pattern = "RoadLink", n_files = Inf) # 100% of GB files
})
```
